import type { SectionTemplate } from '../data/layoutGeometry';
import type { AlbumType } from '../data/albumTypes';

/** Pretty-printed, round-trippable JSON of the whole template registry. */
export function templatesToJSON(templates: Record<string, SectionTemplate>): string {
  return JSON.stringify(templates, null, 2);
}

/**
 * The registry as a TypeScript snippet to paste over the `TEMPLATES` constant
 * in src/data/layouts.ts. (The seed `gridTemplate(...)` calls can then be
 * dropped in favour of this literal once positions are finalised.)
 */
export function templatesToSource(templates: Record<string, SectionTemplate>): string {
  return [
    '// Generated by the dev-only template editor — paste over TEMPLATES in',
    '// src/data/layouts.ts.',
    "import type { SectionTemplate } from './layoutGeometry';",
    '',
    `export const TEMPLATES: Record<string, SectionTemplate> = ${templatesToJSON(
      templates,
    )};`,
    '',
  ].join('\n');
}

/** Pretty-printed, round-trippable JSON of the whole album-type registry. */
export function albumTypesToJSON(types: Record<string, AlbumType>): string {
  return JSON.stringify(types, null, 2);
}

/**
 * The whole album-type registry as a TypeScript module to paste over the
 * ALBUM_TYPES / ACTIVE_ALBUM_TYPE_ID exports in src/data/albumTypes.ts. Every
 * AlbumType is plain data (sections + templates), so the JSON literal is a
 * faithful, round-trippable representation of the registry.
 */
export function albumTypesToSource(
  types: Record<string, AlbumType>,
  activeId: string,
): string {
  return [
    '// Generated by the dev-only album-type builder — paste over ALBUM_TYPES and',
    '// ACTIVE_ALBUM_TYPE_ID in src/data/albumTypes.ts.',
    "import type { AlbumType } from './albumTypes';",
    '',
    `export const ALBUM_TYPES: Record<string, AlbumType> = ${albumTypesToJSON(types)};`,
    '',
    `export const ACTIVE_ALBUM_TYPE_ID = ${JSON.stringify(activeId)};`,
    '',
  ].join('\n');
}
