import type { SectionTemplate } from '../data/layoutGeometry';

/** Pretty-printed, round-trippable JSON of the whole template registry. */
export function templatesToJSON(templates: Record<string, SectionTemplate>): string {
  return JSON.stringify(templates, null, 2);
}

/**
 * The registry as a TypeScript snippet to paste over the `TEMPLATES` constant
 * in src/data/layouts.ts. (The seed `gridTemplate(...)` calls can then be
 * dropped in favour of this literal once positions are finalised.)
 */
export function templatesToSource(templates: Record<string, SectionTemplate>): string {
  return [
    '// Generated by the dev-only template editor — paste over TEMPLATES in',
    '// src/data/layouts.ts.',
    "import type { SectionTemplate } from './layoutGeometry';",
    '',
    `export const TEMPLATES: Record<string, SectionTemplate> = ${templatesToJSON(
      templates,
    )};`,
    '',
  ].join('\n');
}
